### ISSUE TITLE
New CSS tokens - warn and do a mapping for global tokens

### ISSUE THREAD

**Issue by adamviktora** [patternfly/pf-codemods#748]
Follow up to https://github.com/patternfly/pf-codemods/issues/733 

- [x] Provide warnings for Literals too (string like `"var(--pf-v5-whatever)"`) - DONE in https://github.com/patternfly/pf-codemods/pull/755
- [ ] Update every global token, which is not a color token - automatically via a fix.
- [ ] For colors, provide f.e. a hot pink color for every color so the consumers see it and then manually update to use the correct token.
